<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Attax.Core\engine-params.json" Link="engine-params.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Attax.Core\Attax.Core.csproj" />
    <ProjectReference Include="..\Attax.Core.Utils\Attax.Core.Utils.csproj" />
    <ProjectReference Include="..\Attax.Model\Attax.Model.csproj" />
    <ProjectReference Include="..\Attax.Data\Attax.Data.csproj" />
    <ProjectReference Include="..\Attax.Play\Attax.Play.csproj" />
  </ItemGroup>

</Project>
